Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--groups", "/DevOops"]
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true

  (0..1).each do |i|
    config.vm.define "devoops-0#{i}" do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "devoops-0#{i}"

      node.vm.network "public_network",
        bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.1.21#{i}"

      node.vm.provision "shell",
        run: "always",
        inline: "ifconfig | grep 'inet'"
     end
  end
end
