---
- name: add repo key for docker
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    data: "{{ lookup('file', 'docker-ubuntu.asc') }}"
    state: present

- name: add docker repo source for '{{ ansible_distribution_release }}'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: update
  apt:
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce
    state: fixed

- name: docker status
  service:
    name: docker
    enabled: yes
    state: restarted

- name: add user to docker group
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes